Testor:Cofe.o Sale.o Project_2.o Save.o
	gcc -Wall Cofe.o Sale.o Save.o Project_2.o -o Testor
Sale.o:Sale.c
	gcc -c Sale.c
Cofe.o:Cofe.c
	gcc -c Cofe.c
Save.o:Save.c
	gcc -c Save.c
Project_2.o:Project_2.c
	gcc -c Project_2.c
clean:
	rm -f *.o Testor
